
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-ingress
spec:
  rules:
  - host: square
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: sq-svc
            port:
              number: 80
  - host: fibonacci
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: fb-svc
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sq-deployment
  labels:
    app: sq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sq
  template:
    metadata:
      labels:
        app: sq
    spec:
      containers:
      - name: sq
        image: jackmana/sre:all
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        env:
        - name: SERIES_VERSION
          value: square
---
apiVersion: v1
kind: Service
metadata:
  name: sq-svc
spec:
  selector:
    app: sq
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deployment
  labels:
    app: fb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb
  template:
    metadata:
      labels:
        app: fb
    spec:
      containers:
      - name: fb
        image: jackmana/sre:all
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 8000
        env:
        - name: SERIES_VERSION
          value: fibonacci
---
apiVersion: v1
kind: Service
metadata:
  name: fb-svc
spec:
  selector:
    app: fb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http