apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sqName }}
  labels:
    app: {{ .Values.sqName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.sqName }}
  template:
    metadata:
      labels:
        app: {{ .Values.sqName }}
    spec:
      containers:
      - name: {{ .Values.sqName }}
        image: jackmana/sre:all
        resources:
          limits:
            memory: {{ .Values.MEM }}
            cpu: {{ .Values.CPU }}
        ports:
        - containerPort: 8000
        env:
        - name: SERIES_VERSION
          value: {{ .Values.sqName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fbName }}
  labels:
    app: {{ .Values.fbName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fbName }}
  template:
    metadata:
      labels:
        app: {{ .Values.fbName }}
    spec:
      containers:
      - name: {{ .Values.fbName }}
        image: jackmana/sre:all
        resources:
          limits:
            memory: {{ .Values.fbMEM }}
            cpu: {{ .Values.fbCPU }}
        ports:
        - containerPort: 8000
        env:
        - name: SERIES_VERSION
          value: {{ .Values.fbName }}
