apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:     
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        resources:
          limits:
            memory: {{ .Values.resource.limits.memory }}
            cpu: {{ .Values.resource.limits.cpu }}
        ports:
        - containerPort: 8000
        env:
          {{- range $k, $v := .Values.env }}
          - name: {{ $v.name }}
            value: {{ $v.value }}
          {{- end }}



