apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fibonacci.name }}
  labels:
    app: {{ .Values.fibonacci.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.fibonacci.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fibonacci.name }}
    spec:
      containers:
      - name: {{ .Values.fibonacci.name }}
        image: {{ .Values.image }}
        resources:
          limits:
            memory: {{ .Values.fibonacci.resource.limits.memory }}
            cpu: {{ .Values.fibonacci.resource.limits.cpu }}
        ports:
        - containerPort: 8000
        env:
        - name: SERIES_VERSION
          value: {{ .Values.fibonacci.env.SERIES_VERSION }}